### ISSUE TITLE
Pokecubes mobs not being blocked (Mod compatibility)

### ISSUE THREAD

**Issue by AwkwardOne** [Xalcon/TorchMaster#122] opened 2020-05-09 15:20 UTC
Hello,

MC version 1.15.2

Issue: mobs from Pokecubes AIO mod are not being blocked from spawning within the radius of the megatorch. Pokecubes also lay eggs which will hatch new ones but the normal spawning hasn't been hindered by the dread lamp nor mega torch
Thank you.
Torchmaster entity dump: https://pastebin.com/nHPR9kyP

**Comment by Xalcon** [comment] 2020-05-10 00:26
Are the pokecube mobs hostile towards the player? Have you tried the Dread Lamp? According to your entity dump (which is really helpful, thank you for that!), the pokecube mobs have been assigned to the Dread Lamp.

The Megatorch only blocks hostile entities. The Dread Lamp on the other hand should block Non-Hostiles like animals, bats, etc.

**Comment by AwkwardOne** [comment] 2020-05-10 09:59
> Are the pokecube mobs hostile towards the player? Have you tried the Dread Lamp? According to your entity dump (which is really helpful, thank you for that!), the pokecube mobs have been assigned to the Dread Lamp.
> 
> The Megatorch only blocks hostile entities. The Dread Lamp on the other hand should block Non-Hostiles like animals, bats, etc.

I have a dread lamp next tot the mega torch and they keep spawning. I don't know what they are considered as because normally they are passive but sometimes they just feel like attacking you

**Comment by Xalcon** [comment] 2020-05-10 13:50
Pokecube uses its own spawning system, which in itself is fine. The issue is, the devs dont post the proper spawn events to the eventbus that torchmaster relies on (Specifically CheckSpawn). I'm still investigating my options, but this might actually require a change on the Pokecube side.

**Comment by AwkwardOne** [comment] 2020-05-10 18:35
> Pokecube uses its own spawning system, which in itself is fine. The issue is, the devs dont post the proper spawn events to the eventbus that torchmaster relies on (Specifically CheckSpawn). I'm still investigating my options, but this might actually require a change on the Pokecube side.

That's unfortunate, I hope something can be worked out

**Closed as completed** 2022-12-23 09:22 UTC
Labels: investigating, mod compatibility
