### ISSUE TITLE
Block zombie siege mobs

### ISSUE THREAD

**Issue by Rodg88** [Xalcon/TorchMaster#177] opened 2022-02-14 02:19 UTC
Would it be possible to let mega torches block zombie sieges? It's a very annoying vanilla mechanic with no gamerule to disable it. Apparently it's "VILLAGE_INVASION" internally.

**Comment by Delfite** [comment] 2022-03-28 13:23
This would be very nice to have in all versions, since it could let you prevent random invasions from happening.

**Comment by Xalcon** [comment] 2022-03-28 17:46
I've not looked into this for some time. In the past, this was not possible to do without a core mod but I wouldn't be suprised if Forge added events in the meantime to hook into. If someone has more information, I'd appreciate if you post here.

**Comment by Rodg88** [comment] 2022-03-29 23:36
When looking into it I found this spigot mod for it, not sure if it helps https://github.com/dbkynd-minecraft/NoZombieSiege

**Comment by Xalcon** [comment] 2022-03-30 17:00
The link does unfortunately not help. Forge does not have the minecraft mobspawn reason checks hooked up to the forge event system - but in this case, its not necessary. I found out about the `VillageSiegeEvent`, which is pretty much everything I need for this (I hope).

**Comment by Xalcon** [comment] 2022-03-30 17:13
Implemented in version 18.1.0, let me know if you find any issues.

**Comment by lays24mc** [comment] 2022-04-08 11:32
@Xalcon I tested it once in 1.18.2 with the latest TorchMaster version and was just completely surprised by a zombie invasion xD. So apparently the Megatorch does not lock that, despite 128 range

**Comment by Xalcon** [comment] 2022-04-10 08:52
Thats a bit odd. I've been hovering over a village with several torches placed down for close to 4h without a single invasion. 

I'll look into it, but these kind of things are hard to replicate

**Comment by lays24mc** [comment] 2022-04-10 09:06
I have now test now also times a few more torches around the village set. I'll let you know if it brings something. Possibly my village is too big ^^

**Comment by Rodg88** [comment] 2023-04-23 10:27
I've just tested this, and it doesn't seem to be working.

I have v18.1.0, in the vault hunters modpack 8.0.3

I set up 20+ villagers in the middle of a biome that has no natural mob spawns. I then tested without mega torches first by setting time to midnight, and then using the command `time add 23700t` to add almost a full day, so the game passes midnight again. I looked up at the moon, and as soon as the edge of the moon reaches my cursor, i use the time add command again, to skip ahead to the next night just before midnight. I confirmed I got a zombie siege. Set to peaceful and back to normal to clear it.

Then I added a mega torch near the center village, and cycled the nights again, and still got a siege after a few nights.

Added more mega torches around the area but further out, cycled some nights again, and got another siege.

![2023-04-23_20 17 15](https://user-images.githubusercontent.com/2611674/233834291-f3f51f58-b3f6-4095-ac59-cbdd42598112.png)

It looks like in 1.19, there's a tag that can be added to biomes to block sieges `without_zombie_sieges`, but looks like it just might not be easy to block them in 1.18 or earlier

**Comment by Xalcon** [comment] 2023-04-24 06:40
Thank you for your detailed description. I'll attempt recreating it. It bothered me quite a bit that this isn't working

**Comment by Xalcon** [comment] 2024-09-01 11:31
Closing this. I've been testing this in private and was never able to reproduce it. I intent to create a testsuite and with mixins, I should be able to create better testcases that allow me to force raids to occur. For now, it seems the blocking is working as expected though.

**Closed as completed by Xalcon** 2024-09-01 11:31 UTC
Labels: feature, implemented
