### ISSUE TITLE
[Bug]: Server Crash due to incorrect number of arguments

### ISSUE THREAD

**Issue by morris179** [Xalcon/TorchMaster#243] opened 2024-10-16 18:00 UTC
### Torchmaster Version

21.1.2

### Mod Loader

Fabric

### Mod Loader Version

0.16.2

### What happened?

Not sure what exactly happened, but the server keeps crashing every 12-24 hours with the crash reports that's below.

### Relevant log output

```shell
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2024-10-16 17:25:56
Description: Exception ticking world

com.llamalad7.mixinextras.injector.wrapoperation.IncorrectArgumentCountException: Incorrect number of arguments passed to Operation::call! Expected 3 but got 2. Expected types were [net.minecraft.class_1419, net.minecraft.class_3218, net.minecraft.class_2338], actual types were [net.minecraft.class_3218, net.minecraft.class_2338].
	at com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationRuntime.checkArgumentCount(WrapOperationRuntime.java:10)
	at net.minecraft.class_1419.mixinextras$bridge$method_6448$7(class_1419.java)
	at net.minecraft.class_1419.wrapOperation$bip000$torchmaster$tryToSetupSiege_findRandomSpawnPos(class_1419.java:534)
	at net.minecraft.class_1419.method_6446(class_1419.java:95)
	at net.minecraft.class_1419.method_6445(class_1419.java:56)
	at net.minecraft.class_3218.method_29202(class_3218.java:444)
	at net.minecraft.class_3215.method_14161(class_3215.java:372)
	at net.minecraft.class_3215.method_12127(class_3215.java:310)
	at net.minecraft.class_3218.method_18765(class_3218.java:350)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.class_3176.method_3813(class_3176.java:299)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationRuntime.checkArgumentCount(WrapOperationRuntime.java:10)
	at net.minecraft.class_1419.mixinextras$bridge$method_6448$7(class_1419.java)
	at net.minecraft.class_1419.wrapOperation$bip000$torchmaster$tryToSetupSiege_findRandomSpawnPos(class_1419.java:534)
	at net.minecraft.class_1419.method_6446(class_1419.java:95)
	at net.minecraft.class_1419.method_6445(class_1419.java:56)
	at net.minecraft.class_3218.method_29202(class_3218.java:444)
	at net.minecraft.class_3215.method_14161(class_3215.java:372)
	at net.minecraft.class_3215.method_12127(class_3215.java:310)
```

**Comment by Xalcon** [comment] 2024-10-16 18:38
This is caused by one of the features that were previously hard to test: Village Sieges. There is no builtin way to force a village siege, but I did find the error, small mistake on my side. I've added a torchmaster subcommand to force setup village sieges now, to make sure i can test this in the future when needed.

Fixed in 21.1.4
Available via [Github Releases](https://github.com/Xalcon/TorchMaster/releases/tag/mc1.21.1-21.1.4-beta) or Modrinth and Curseforge (once approved)

Thanks for reporting the issue.

**Closed as completed** 2024-10-20 10:08 UTC
Labels: bug, fixed
