### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by frenzye** [Xalcon/TorchMaster#19] opened 2017-05-16 01:15 UTC
Getting this client crash, not sure where to go with it 

https://gist.github.com/frenzye/2703f934ffdbac4b3e28991e8e242544

**Comment by Xalcon** [comment] 2017-05-16 15:11
This error seem to be related to something with better builders wand. I'll take a closer look at it when I get home. Thanks for the report.

**Comment by Xalcon** [comment] 2017-05-16 16:00
I was able to replicate the issue with the mega torch as well as a normal vanilla minecraft torch.
It seems the problem is on side of BetterBuildersWand.
I will leave this open for now, but I cant do anything on my side to fix this issue.
https://github.com/portablejim/BetterBuildersWands/issues/47

**Comment by Xalcon** [comment] 2017-05-17 07:55
The crash happens due to NetherEx trusting the values passed to `Block#pickBlock()`, but BetterBuildersWands passes a wrong coordinate which causes the NetherEx block to crash. NetherEx no longer supports 1.10.2 and even then, its BetterBuildersWands fault for passing invalid values imho.

Since the bug is not directly related to Torchmaster (just easy to replicate with it, should be just as simple to replicate with a fence tho) ill close this here.

**Closed by Xalcon** 2017-05-17 07:55 UTC
Labels: invalid
