### ISSUE TITLE
Frozen Pearl works but then undoes itselfv. 18.1.0

### ISSUE THREAD

**Issue by DakaraMCE** [Xalcon/TorchMaster#196] opened 2022-11-21 03:25 UTC
I use the pearl after removing nearby feral flare lanterns and moments later it returns.  its ruining my cursed dirt mob farm.

**Comment by Xalcon** [comment] 2022-12-23 09:33
Unfortunately, this is working as intended - for now. The Feral Flare Lantern does not take Line of Sight into account. This will be added back in, soon™️

Closing as duplicate of #174

**Closed as not planned** 2022-12-23 09:46 UTC
