### ISSUE TITLE
Gui of flare lantern wont show up 

### ISSUE THREAD

**Issue by Karnatour** [Xalcon/TorchMaster#197] opened 2022-12-08 16:50 UTC
Hey i am playing enigmatica 6 and when i right click on flare lantern nothing shows up

**Comment by Xalcon** [comment] 2022-12-23 09:44
Yes, this is expected. The way GUIs work was changed in one of minecrafts updates and I never got around updating it. It's on my todo list.

Closed as duplicate of #174

**Closed as not planned** 2022-12-23 09:50 UTC
