### ISSUE TITLE
[1.16.1] [torchmaster-2.3.1-alpha] Crash when vines / Quark's roots grow onto invisible light

### ISSUE THREAD

**Issue by Blazingi** [Xalcon/TorchMaster#133] opened 2020-08-13 00:46 UTC
[crash-2020-08-13_02.23.02-server.txt](https://github.com/Xalcon/TorchMaster/files/5066543/crash-2020-08-13_02.23.02-server.txt)
[crash-2020-08-11_01.04.16-server.txt](https://github.com/Xalcon/TorchMaster/files/5066544/crash-2020-08-11_01.04.16-server.txt)
[crash-2020-08-11_00.21.27-server.txt](https://github.com/Xalcon/TorchMaster/files/5066545/crash-2020-08-11_00.21.27-server.txt)
`java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=east, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{torchmaster:invisible_light}
	at net.minecraft.state.StateHolder.func_206870_a(SourceFile:114) ~[?:?] {re:classloading}
	at net.minecraft.block.VineBlock.func_196544_a(VineBlock.java:228) ~[?:?] {re:classloading}
	at net.minecraft.block.VineBlock.func_225542_b_(VineBlock.java:212) ~[?:?] {re:classloading}`
Happens regulary with Feral Lanterns, and goes away when random tick is set to 0.

**Comment by Xalcon** [comment] 2020-08-13 06:55
duplicate of #132

**Closed as completed by Xalcon** 2020-08-13 06:55 UTC
Labels: duplicate

**Comment by Xalcon** [comment] 2020-08-13 19:09
I've deployed a potential fix with version 2.3.2. Can you verify this is working for you as well?

**Comment by Blazingi** [comment] 2020-08-15 01:15
It all seems fine now, thank you!
