### ISSUE TITLE
[Bug]: Feral Flare Lantern n Mega Torch Issue

### ISSUE THREAD

**Issue by PoncikMarket** [Xalcon/TorchMaster#236] opened 2024-09-04 09:47 UTC
### Torchmaster Version

21.0.0

### Mod Loader

Neoforge

### Mod Loader Version

21.1.34

### What happened?

I'm playing on a my own server. Modpack ATM10. The issue is exactly this, when I place a Feral Flare Lantern or Mega Torch under my platform, there are textures such as strange light filters on the platform surface and no blocks are placed at those points.

**Comment by Xalcon** [comment] 2024-09-04 16:06
I don't think this is a Torchmaster issue. Both the Feral Flare Lantern and Mega Torch are the same as normal torches. Can you provide a screenshot of the issue?

**Comment by PoncikMarket** [comment] 2024-09-04 16:14
I can send video with streamable

**Comment by PoncikMarket** [comment] 2024-09-04 16:19
[https://streamable.com/2suzw0](url)

**Comment by PoncikMarket** [comment] 2024-09-04 16:22
![1](https://github.com/user-attachments/assets/7a4a97b7-d1ff-4340-868d-f17039651fe4)
In a video it was 3 but now its increasing lmao

**Comment by Xalcon** [comment] 2024-09-04 16:24
Those lights are from the Feral Flare Lantern, they are supposed to be replaceable but there was a bug which prevented it. This bug was already fixed in 21.0.1

Duplicate of #234

**Comment by PoncikMarket** [comment] 2024-09-04 16:30
Okey thanks, but i cant update ATM10 pack to 0.45 version (its have torchmaster 21.0.1). 0.45 is broken give error i told them but waiting. Thanks sir

**Closed as completed** 2024-09-05 14:09 UTC
Labels: bug, duplicate
