### ISSUE TITLE
1.12.2 Lycanites spawn bug

### ISSUE THREAD

**Issue by chidorrasen** [Xalcon/TorchMaster#105] opened 2019-11-18 19:47 UTC
hello, i have a world with lots of mods installed but i never had any problem with the spawn thanks to torchmaster, i placed a megatorch in a village and i made my base just at the border outside of the range. in that way the villagers were well protected and i could still have a challenge 

lately i started to get a bit bored of the mods i had so i decided to install lycanites and made sure that the option in the torchmaster config to prevent lycanites was turned on, but i found that the village was full of Lycanites mobs like they didnt care about the megatorch.

before i posted here i made sure in other world that they were in fact spawning and not walking in
![Sin título](https://user-images.githubusercontent.com/8070342/69083507-85f88f00-0a42-11ea-9bc4-4b2b8d9eba0e.png)

Minecraft 1.12.2
Forge 14.23.5.2847
Lycanites 2.0.1.5
Torchmaster 1.8.0.79
megatorch range is set to 100
B:LycanitesMobsBlockAll=true

it blocks all the other enemies from other mods and only failed when i added Lycanites

tried setting slighlyMoreAggressiveBlocking to true, didn´t work

**Comment by Xalcon** [comment] 2019-11-18 20:22
Hm... interesting. What Biome was that? I'll look into it.

**Comment by Xalcon** [comment] 2019-11-18 20:31
I think I found the issue already. Back in 1.10 lycanites mobs used different mod names per set of mobs (so instead of just "lycanitesmobs", some mobs were part of a mod "arcticmobs" while others were "demonmobs" etc). Looks like this was changed - not sure when tho. I'll make a quick fix.

**Comment by Xalcon** [comment] 2019-11-18 21:10
Fix is up on Curseforge, awaiting approval. Can you check Version 1.8.1 (once approved by curse) if the issue is indeed fixed for you? Ty.

**Comment by chidorrasen** [comment] 2019-11-18 22:56
that was realy fast! i just tried and seems like the new version is working fine, right now they are all spawning outside of the range, i dont have time to try spawners and everything right now, but if i find something else failing i will make a new report

thank you!

**Comment by Xalcon** [comment] 2019-11-18 23:09
Alright, closing this then. :)

**Closed by Xalcon** 2019-11-18 23:09 UTC
Labels: bug
