### ISSUE TITLE
TorchMaster does not work with Custom Mob Spawner

### ISSUE THREAD

**Issue by UnixRonin** [Xalcon/TorchMaster#13] opened 2017-04-24 14:24 UTC
Pretty straightforward:  Dr.Zhark's Mo'Creatures does not use the vanilla spawner, it uses its own spawner, Custom Mob Spawner, which takes over all spawning because the vanilla spawner won't spawn Mo'Creatures mobs.  TorchMaster has no effect on CMS spawning, so if Mo'Creatures is installed, TorchMaster doesn't work.  I don't know if this is fixable by Torchmaster or not.

(I imagine it goes without saying that it almost certainly won't work with Lycanite's Mobs either, because Lycanite's Mobs **deliberately** ignores **ALL** spawning controls.)

**Comment by Xalcon** [comment] 2017-04-24 17:37
I'm not sure if I understand your issue. The Torch is only supposed to block spawning from low light levels (natural spawning). I dont want to break monster farms, hence why I added special support for vanilla spawners (and extra utilities). If the spawners keep spawning entities, this is intended behavior. If the spawners dont work on the other hand, its a bug and I will need to fix that.

**Comment by Xalcon** [comment] 2017-04-24 18:01
I've tested the following mods:
* Torchmaster 1.2.1.23
* DrZhark's CustomSpawner 3.10.1
* DrZhark's Mo'Creatures Mod 10.0.6
I was not able to replicate any issues with the Mega Torch. No natural spawning occured inside the torch volume. Only a few critters (Bugs, cats, moles, etc) were spawning since there arent considered being aggressive entities. Spawning of non-aggressive entities is successfully blocked by the dread lamp.

I would like you to report back on this if you can replicate the problem or if you have more information about the issue.

**Comment by Xalcon** [comment] 2017-04-24 19:19
I can confirm, some of Lycanite's Mobs are not blocked by the Mega Torch. Issues related to Lycanite's Mobs should be handled in #14 for now.

**Comment by UnixRonin** [comment] 2017-04-25 04:19
I'm surprised **any** of the Lycanite mobs are blocked.  :)

The issue I had was that the Mega Torch did not seem to be blocking any Mo'Creatures spawns at all.  We put up torches and continued to get full monster spawning.

It does seem to be working better now; I'm not sure what changed.

**Comment by Xalcon** [comment] 2017-04-25 09:15
I dont want to rule out any issues with Mo'Creatures spawns, due to the issues with Lycanite's Mobs. If you can replicate the issue (maybe with a specific creature) it would be really helpful.
Sadly, Mo'Creatures is not open source and afaik, decompiling is not prohibited, which makes the whole issue much harder to debug.

**Comment by UnixRonin** [comment] 2017-04-25 12:17
I'll try to replicate it.  I'm also scratching my head over why it initially had no effect but seems to be working now.  Could the server being restarted since the torches were placed have had anything to do with it?

**Comment by Xalcon** [comment] 2017-04-25 20:26
This could be one reason, but I doubt it. A torch registers itself in a registry when the torch is loaded and unregisters itself when the chunk is being unloaded.

If - for some reason - this registration process is not working, the torch will effectivly not work. Replacing the torch or leaving the area and going back to it should fix it though. But like I said, I dont think this happens. 

I will close this issue for now. Please report back to this issue if you have any news. I will reopen the issue, if necessary.
Thanks for your feedback so far 😄 

/close

**Closed by Xalcon** 2017-04-25 20:26 UTC
Labels: cant reproduce
