### ISSUE TITLE
Compatibility with Carry On

### ISSUE THREAD

**Issue by GStefanowich** [Xalcon/TorchMaster#230] opened 2024-04-15 01:34 UTC
Using
- Minecraft `1.20.1`
- Neoforge `47.1.101`
- [Carry On](https://github.com/Tschipp/CarryOn) `2.1.2.7` ([Modrinth](https://modrinth.com/mod/carry-on))
- TorchMaster `20.1.5`

Not sure if this is better solved from the side of CarryOn or TorchMaster.

CarryOn pickups destroy the mob entity, and spawn a new mob entity upon being placed. The Dread lamp will prevent mobs from being placed back down because it voids them

**Comment by Xalcon** [comment] 2024-04-15 07:28
It never even occured to me that someone might want to move the torch using carry on - I mean, why would you? Destroying and placing the torch or lamp work just as fine and provide the intended behavior. 

I'm actually not sure what exactly I should be doing differently. At the moment, the torch and lamp are registering themselves with their respective Registry via the `Block::onPlace` method. 
https://github.com/Xalcon/TorchMaster/blob/07bd2cc417e09248c7060727c3954275c89f1d9b/src/main/java/net/xalcon/torchmaster/common/blocks/EntityBlockingLightBlock.java#L54-L61

Neither the Mega Torch nor the Dread Lamp are a Tile Entity - they are Plain Blocks. If Carry On calls `Block::onRemove` on pick up and `Block::onPlace` on place down, the registration logic should work.

This whole thing willl most likely change with 1.21 as I'm in the process of moving to a multi modloader solution which requires a major rewrite of the mod. But in the meantime, I'm not sure what else I could do to get this to work from my side.

**Comment by GStefanowich** [comment] 2024-04-15 08:21
> It never even occured to me that someone might want to move the torch using carry on

You misunderstand me,

> CarryOn pickups destroy **the mob entity**

If you pick up a passive mob with CarryOn, and place it near a Dread Lamp, the dread lamp deletes **the mob**.

**Comment by Xalcon** [comment] 2024-04-15 08:26
oh, I'm sorry. That makes more sense.
This might be somewhat simple to fix from my side. It seems Forge introduced a new event type which Torchmaster didn't handle properly. I'll try to provide a fix.

**Comment by Xalcon** [comment] 2024-04-15 08:44
Fixed in Version 20.1.6
I've added the missing event as an intentional spawn event - I hope this doesnt break other mods in the process, but time will tell.

The update should be available on [modrinth](https://modrinth.com/mod/torchmaster/versions) and the [github release section](https://github.com/Xalcon/TorchMaster/releases). For some reason, curseforge is taking longer again.

**Comment by GStefanowich** [comment] 2024-04-15 08:46
That's fantastic, I'm glad that it was a simpler fix. Greatly appreciated

**Closed as completed** 2024-04-15 08:52 UTC
Labels: bug, fixed
