### ISSUE TITLE
"torch is not valid" spamming in console

### ISSUE THREAD

**Issue by Tkdmaster** [Xalcon/TorchMaster#46] opened 2017-12-14 16:48 UTC
Hey, just as the title says, I was going pregen on my world when this started happening:
https://i.imgur.com/Z4e7aT6.png

Update: I finished the world pregen and restarted the server, now the console is just flooding with those same lines over and over.

**Comment by KasperFranz** [comment] 2018-01-12 18:56
We got the same issue running the latest Revelations modpack - any ETA on the cause or fix for this :)?

**Comment by Spaig** [comment] 2018-01-19 22:15
We have this too! It's not a dealbreaker, but it does make the logs a LOT harder to make use of,

**Comment by JumpyDragon** [comment] 2018-01-28 06:36
Yes, ditto that, Spaig. I'm only playing SSP and even then it stops recording because my logs get too long due to this invalid torch spam. But I really depend on the TorchMaster mod for lighting aesthetics (avoiding absurd light pollution with torches every however many blocks). So it would be very nice to see a fix, or at least a way to exclude it from the logs.

**Comment by Explosivee** [comment] 2018-02-18 20:38
I have this too, really annoying.

**Comment by jaeblaze1989** [comment] 2018-02-21 23:25
same issue on my server.   

```
22.02 10:24:07 [Server] Server thread/INFO [torchmaster]: Torch @ DIM: 0 - BlockPos{x=4951, y=66, z=1355} is no longer valid, removing from registry
22.02 10:24:07 [Server] Server thread/INFO [torchmaster]: Torch @ DIM: 0 - BlockPos{x=4951, y=66, z=1355} is no longer valid, removing from registry
22.02 10:24:07 [Server] Server thread/INFO [torchmaster]: Torch @ DIM: 0 - BlockPos{x=4951, y=66, z=1355} is no longer valid, removing from registry
22.02 10:24:07 [Server] Server thread/INFO [torchmaster]: Torch @ DIM: 0 - BlockPos{x=4951, y=66, z=1355} is no longer valid, removing from registry
22.02 10:24:07 [Server] Server thread/INFO [torchmaster]: Torch @ DIM: 0 - BlockPos{x=4951, y=66, z=1355} is no longer valid, removing from registry
22.02 10:24:08 [Server] Server thread/INFO [torchmaster]: Torch @ DIM: 0 - BlockPos{x=4951, y=66, z=1355} is no longer valid, removing from registry
22.02 10:24:08 [Server] Server thread/INFO [torchmaster]: Torch @ DIM: 0 - BlockPos{x=4951, y=66, z=1355} is no longer valid, removing from registry
```
went to that location and there is nothing there. tried placing a torch from the mod and removing. same issue.

**Comment by hqpwca** [comment] 2018-02-25 13:47
same issue

**Comment by jaeblaze1989** [comment] 2018-02-26 01:04
I fixed the issue by deleting the torch master registry file

**Comment by KasperFranz** [comment] 2018-02-28 09:41
The main question is - is it really needed?

**Comment by Morpheus1101** [comment] 2018-03-02 23:33
Any updates or further information in regardswwwww to this issue ?

**Closed** 2018-05-02 12:45 UTC
Labels: bug

**Comment by jaeblaze1989** [comment] 2018-05-02 21:15
The torch not being there is what caused the issue for me in the first place. Had to delete the master registry file to fix. Happened multiple times.

**Comment by Xalcon** [comment] 2018-05-03 05:55
i'm actually baffled how this could happen, especially after a server reboot. There was a bug that caused the message to appear but since i forgot to actually remove the torch from the registry, it would recheck that position every so often, causing this spam to appear. The question is, why was the torch missing in the first place? 🤔

**Comment by Spaig** [comment] 2018-05-03 06:35
in our case, it was because we did some world editing and a whole area of the world got shuffled around and de-torched. That's not the mod's fault of course, but we did have to yank Torchmaster to stop the console spam.

**Comment by Xalcon** [comment] 2018-05-03 07:16
yeah, i figured these edge cases can happen. Torchmaster shouls behave much better now, sorry for the inconvenience.
